// <auto-generated />
using System;
using Lab10_Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab10_Api.migrations
{
    [DbContext(typeof(MySqlDbcontext))]
    partial class MySqlDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Lab10_Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb5088c6-6564-2dc9-adcc-da90e1ab9821"),
                            Name = "Gorgeous Cotton Pants",
                            Price = 114.287376557790874m
                        },
                        new
                        {
                            Id = new Guid("17c5017a-d246-3e07-5546-04f053a4e7e3"),
                            Name = "Small Wooden Chair",
                            Price = 641.835813126082501m
                        },
                        new
                        {
                            Id = new Guid("067cde77-728b-c736-4c17-8d24a388fb66"),
                            Name = "Generic Cotton Gloves",
                            Price = 943.108157354431006m
                        },
                        new
                        {
                            Id = new Guid("6152eb29-9afe-414d-7207-3315b147d009"),
                            Name = "Practical Steel Keyboard",
                            Price = 267.268843842061717m
                        },
                        new
                        {
                            Id = new Guid("4a56aee3-9207-85f1-a522-7a10b11f42ff"),
                            Name = "Practical Soft Computer",
                            Price = 983.944050964075981m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
